### PR TITLE
Fix benchmark tests

### PR DESCRIPTION
**Pull request by Pessimistress**

### CODE REVIEW

**Comment by jlisee** [comment]
I would recommend putting this into the diff description:


```
Run `yarn bench-browser` and see something like this in a browser:

PARSE XVIZ
├─ xviz#parseMetadata: 122K iterations/s
├─ xviz#parseFrame: 149K iterations/s
├─ xviz#parseStylesheet: 29.4K iterations/s

Completed benchmark in 0.798s
```

**Comment by jlisee** [comment]
You also need more iterations in these I am seeing a large amount of variability here (from ~30% in some cases).  Do we have a warm up period first to let the JIT get setup?

**Comment by Pessimistress** [comment]
> Do we have a warm up period first to let the JIT get setup?

Not at the moment. This needs to be fixed on the `@probe.gl/bench` end.

**Comment by Pessimistress** [comment]
@jlisee The current benchmark cases are actually too trivial. I need to get better test data.

**Pull request merged**
